name: Unity CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity License
        uses: game-ci/unity-builder@v4 
        with:
          version: 6000.0.34f1
          license: ${{ secrets.UNITY_LICENSE }}  
          email: ${{ secrets.UNITY_EMAIL }} 
          password: ${{ secrets.UNITY_PASSWORD }}  

      - name: Run Unit Tests
        run: |
          ./unity/Editor/Unity -batchmode -nographics -logFile -projectPath . -executeMethod UnityEditor.TestTools.TestRunner.Api.ExecuteTests

      - name: Upload test results
        uses: actions/upload-artifact@v4  # Latest version of artifact upload action
        with:
          name: test-results
          path: /path/to/test/results.xml
