name: Unity CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity License
        uses: game-ci/unity-actions/license@v2  
        with:
          unity_email: ${{ secrets.UNITY_EMAIL }}
          unity_password: ${{ secrets.UNITY_PASSWORD }}
          unity_license: ${{ secrets.UNITY_LICENSE }}

      - name: Set up Unity
        uses: game-ci/unity-builder@v2  
        with:
          version: 6000.0.34f1

      - name: Run Unit Tests
        run: |
          ./unity/Editor/Unity -batchmode -nographics -logFile -projectPath . -executeMethod UnityEditor.TestTools.TestRunner.Api.ExecuteTests

      - name: Upload test results
        uses: actions/upload-artifact@v4  
        with:
          name: test-results
          path: /path/to/test/results.xml
