name: Unity CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}

      - name: Check Unity Credentials
        run: |
          if [ -z "${{ secrets.UNITY_EMAIL }}" ] || [ -z "${{ secrets.UNITY_PASSWORD }}" ]; then
            echo "UNITY_EMAIL or UNITY_PASSWORD not set"
            exit 1
          fi
          echo "Unity credentials found. Proceeding with activation..."

      - name: Activate Unity License
        run: |
          # Unity Activation using email and password
          curl -sSL https://download.unity3d.com/download_unity/activate | \
          UNITY_EMAIL="${{ secrets.UNITY_EMAIL }}" UNITY_PASSWORD="${{ secrets.UNITY_PASSWORD }}" bash
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Set up Unity
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.0.34f1

  build:
    name: Build Unity Project
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}

      - name: Check Unity Credentials
        run: |
          if [ -z "${{ secrets.UNITY_EMAIL }}" ] || [ -z "${{ secrets.UNITY_PASSWORD }}" ]; then
            echo "UNITY_EMAIL or UNITY_PASSWORD not set"
            exit 1
          fi
          echo "Unity credentials found. Proceeding with activation..."

      - name: Activate Unity License
        run: |
          # Unity Activation using email and password
          curl -sSL https://download.unity3d.com/download_unity/activate | \
          UNITY_EMAIL="${{ secrets.UNITY_EMAIL }}" UNITY_PASSWORD="${{ secrets.UNITY_PASSWORD }}" bash
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.34f1
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameBuild
          path: build/
